### ISSUE TITLE
Clean up logs

### ISSUE THREAD

**Issue by jakobherdt** [retest/rebazer#14]
First, we should adapt the log level globally. For instance, processing a repo or a pull request should be on `DEBUG` level.
Second, we should use [parameterized messages](https://www.slf4j.org/faq.html#logging_performance) via the SLF4J API.

**Comment by beatngu13** [comment]
@jakobherdt this is not done. There're are still logs that use the `+` operator respectively no SLF4J parameters (e.g. [here](https://github.com/retest/rebazer/blob/master/src/main/java/org/retest/rebazer/service/BitbucketService.java#L132)).

We also want to add further debug information. Let's discuss this next week.
