### ISSUE TITLE
Merge after one approval or after approval of all reviewers?

### ISSUE THREAD

**Issue by martin-v** [retest/rebazer#31]
As default I like one approval, but sometimes I want explicit that all approver must review the code.

I suggest implementing a support of '@all' in the title of a pull request. Benefits:
* It's visible in the overview of pull requests
* Simple to implement
* Works with all type of git hosting platforms

**Comment by martin-v** [comment]
**poke** @roesslerj @modulo11

**Comment by IgorAlbert** [comment]
Closed with #115

**Comment by beatngu13** [comment]
Reoopen due to https://github.com/retest/recheck.cli/pull/103.

**Comment by IgorAlbert** [comment]
Closed with #115, the changes are just not live.
