### ISSUE TITLE
Do not merged unrebased PRs

### ISSUE THREAD

**Issue by roesslerj** [retest/rebazer#49]
Should not happen:

[retest/rebazer] Feature/better exception handling (#47)
Rebase failed, this pull request needs some manual love ...

[retest/rebazer] Feature/better exception handling (#47)
@roesslerj approved this pull request.

[retest/rebazer] Feature/better exception handling (#47)
Merged #47 into develop.

**Comment by martin-v** [comment]
Isn't a issue, the error message was from another bug which is fixed
